### ISSUE TITLE
findPhoneNumbers doesn't find numbers if followed by opening parenthesis

### ISSUE THREAD

**Issue by pauln** [catamphetamine/libphonenumber-js#252]
findPhoneNumbers doesn't seem to be able to find phone numbers if followed by an opening parenthesis.  For example, in the "Find phone numbers" section of [the live demo](https://catamphetamine.github.io/libphonenumber-js/), try adding some text in parentheses after one of the numbers:
> The number is +7 (800) 555-35-35 and not (213) 373-4253 (that's not even in the same country!) as written in the document.

Now only the first number will be detected.  Parentheses elsewhere in the text are fine:
> The number is +7 (800) 555-35-35 and not (213) 373-4253 as written in the document (it's not even in the same country!).

will still find both numbers.

It strikes me that some people may also write the extension number in parentheses:
> (213) 373-4253 (ext. 234)

which also prevents the entire number from being detected - so a fix for this issue would ideally also detect an extension number if it's surrounded by parentheses.

**Comment by catamphetamine** [comment]
Fixed in `libphonenumber-js@1.4.9`.

**Comment by pauln** [comment]
Thanks for the amazingly quick turnaround on this, @catamphetamine - though it seems that a few cases are still broken:

Input | Status
------- | -------
(213) 373-4253 | Working
(213) 373-4253 (foo) | Working
(foo) (213) 373-4253 | Not detected
(213) 373-4253 () | Not detected
(213) 373-4253 (123) | Not detected
(213) 373-4253 (123 foo) | Not detected
(213) 373-4253 (ext. 123) | Not detected 
(213) 373-4253 (x. 123) | Not detected
(213) 373-4253 (between 12 and 3pm) | Working
(213) 373-4253 ext. 123 | Working
(213) 373-4253 ext. 123 () | Working
(213) 373-4253 ext. 123 (123) | Working
(also try (213) 373-4253) | Not detected
(also try (213) 373-4253 ) | Not detected
(also try (213) 373-4253 if no answer) | Working
((213) 373-4253 if no answer) | Not detected
((213) 373-4253) | Not detected
((213) 373-4253 | Not detected
) (213) 373-4253 | Not detected
(213) 373-4253) | Not detected

It seems as though it fails if followed by parentheses which contain a plausible continuation of the number (i.e. numbers or an extension in a known/accepted format), or if preceded by a parenthesis (opening or closing, either directly or with only whitespace between it and the number) or followed by a closing parenthesis (with or without intervening whitespace).

**Comment by catamphetamine** [comment]
Ha, I see, so you came up with extensive testing...
Yeah, the fix I pushed previously was a "quick" one: some kind of a simple patch to plug that specific hole.
Turns out there was too many of them, so I decided to finish porting the original Java `findNumbers()` functions.
Released it as part of `libphonenumber-js@1.5.0`.

Changelog:

  * Deprecated `findPhoneNumbers()`, `searchPhoneNumbers()` and `PhoneNumberSearch`. Use `findNumbers()`, `searchNumbers()` and `PhoneNumberMatcher` instead. The now-deprecated functions were a half-self-made implementation of Google's Java `findNumbers()` until the port of Java code was ported into javascript and passed tests. The port of Google's Java implementation is supposed to find numbers more correctly. It hasn't been tested by users in production yet, but the same tests as for the previous implementation of `findPhoneNumbers()` pass, so seems that it can be used in production.
